export enum Screens {
	LOGIN = 'LOGIN',
	DASHBOARD = 'DASHBOARD',
	ABOUTTHEBAND = 'ABOUTTHEBAND',
	ARTISTDASHBOARD = 'ARTISTDASHBOARD',
	EDITPROFILE = 'EDITPROFILE',
	PROFILE = 'PROFILE',
	REGISTER = 'REGISTER',
	BANDEVENTS = 'BANDEVENTS',
	MAINSETTINGS = 'MAINSETTINGS',
}
