export enum Screens {
	LOGIN = 'LOGIN',
	SINGUP = 'SINGUP',
	DASHBOARD = 'DASHBOARD',
	ABOUTTHEBAND = 'ABOUTTHEBAND',
	ARTISTDASHBOARD = 'ARTISTDASHBOARD',
	EDITPROFILE = 'EDITPROFILE',
	PROFILE = 'PROFILE',
}
